# Generated by Django 4.0.3 on 2022-05-24 17:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0004_alter_answer_author_alter_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': (('can_update_question', 'update_question'),), 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('author', 'text_of_question'), ('text_of_question', 'answer')},
        ),
    ]
