# Generated by Django 4.0.3 on 2022-05-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_answer_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'permissions': (('can_update_answer', 'update_answer'), ('can_delete_answer', 'delete_answer'), ('can_create_answer', 'create_answer')), 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('can_update_comment', 'update_comment'), ('can_delete_comment', 'delete_comment'), ('can_create_comment', 'create_comment')), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': (('can_update_question', 'update_question'), ('can_delete_question', 'delete_question'), ('can_create_question', 'create_question')), 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
