# Generated by Django 4.0.3 on 2022-05-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_answer_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано?'),
        ),
    ]
